### ISSUE TITLE
Error when generating preview images for prompt-sets

### ISSUE THREAD

**Issue by Falls-From-Tree** [dr413677671/PromptGallery-stable-diffusion-webui#12]
When following the tutorial in the readme and using the default avatars.yaml and tags.yaml files I get the error bellow. It looks like extra \ got added into the output path at the end for some reason?
```
Traceback (most recent call last):
  File "D:\xxx\xxxxxxx\stable-diffusion-webui\modules\call_queue.py", line 45, in f
    res = list(func(*args, **kwargs))
  File "D:\xxx\xxxxxxx\stable-diffusion-webui\modules\call_queue.py", line 28, in f
    res = func(*args, **kwargs)
  File "D:\xxx\xxxxxxx\stable-diffusion-webui\modules\txt2img.py", line 46, in txt2img
    processed = modules.scripts.scripts_txt2img.run(p, *args)
  File "D:\xxx\xxxxxxx\stable-diffusion-webui\modules\scripts.py", line 328, in run
    processed = script.run(p, *script_args)
  File "D:\xxx\xxxxxxx\stable-diffusion-webui\scripts\prompt_gallery.py", line 692, in run
    proc = process_images(copy_p)
  File "D:\xxx\xxxxxxx\stable-diffusion-webui\modules\processing.py", line 464, in process_images
    res = process_images_inner(p)
  File "D:\xxx\xxxxxxx\stable-diffusion-webui\modules\processing.py", line 607, in process_images_inner
    images.save_image(image, p.outpath_samples, "", seeds[i], prompts[i], opts.samples_format, info=infotext(n, i), p=p)
  File "D:\xxx\xxxxxxx\stable-diffusion-webui\modules\images.py", line 536, in save_image
    _atomically_save_image(image, fullfn_without_extension, extension)
  File "D:\xxx\xxxxxxx\stable-diffusion-webui\modules\images.py", line 516, in _atomically_save_image
    image_to_save.save(temp_file_path, format=image_format, quality=opts.jpeg_quality, pnginfo=pnginfo_data)
  File "D:\xxx\xxxxxxx\stable-diffusion-webui\venv\lib\site-packages\PIL\Image.py", line 2317, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\xxx\\xxxxxxxx\\stable-diffusion-webui\\extensions\\PromptGallery-stable-diffusion-webui\\assets\\preview\\General_ice_high_res\\00000-0-flowing ice, portrait, focus on face, complex, extremely detailed , elegant, CG,  (an extremely delicate and beautiful girl), in.tmp'
```

**Comment by dr413677671** [comment]
It seems like you did not use the latest version. Please git pull webui and reinstall the latest version of prompt gallery.

The latest verion should fix the bug.

If it still happens. Please try not not add any file generation setup in the first column

![image](https://user-images.githubusercontent.com/32362729/207642324-a644f7be-d0b0-4007-ae92-9d2eae1f6634.png)

**Comment by Falls-From-Tree** [comment]
I am still current with the webui, and I just deleted Prompt Gallery in my extension folder and reinstalled it through the webui and got the same error. I also checked in my settings and I don't mess with any of the default paths or file naming settings in there. Do you know which file had the bug in it so I could check it myself on my machine?

**Comment by Falls-From-Tree** [comment]
I am still current with the webui, and I just deleted Prompt Gallery in my extension folder and reinstalled it through the webui and got the same error. I also checked in my settings and I don't mess with any of the default paths or file naming settings in there. Do you know which file had the bug in it so I could check it myself on my machine?

**Comment by Falls-From-Tree** [comment]
I am still current with the webui, and I just deleted Prompt Gallery in my extension folder and reinstalled it through the webui and got the same error. I also checked in my settings and I don't mess with any of the default paths or file naming settings in there. Do you know which file had the bug in it so I could check it myself on my machine? 

(also sorry for the weird comment editing here I don't know how this works)

**Comment by dr413677671** [comment]
Could you screenshot your config page?

**Comment by dr413677671** [comment]
I could not repro from my side.

**Comment by Falls-From-Tree** [comment]
Here's the saving settings, I can send the whole page too if that's needed

![saving images](https://user-images.githubusercontent.com/36825711/208232213-97900e10-9769-4e31-95f8-9d152874aba1.PNG)
![paths of saving](https://user-images.githubusercontent.com/36825711/208232211-10eb264e-dec1-46af-bffd-f39d2234e69d.PNG)
![webui-user screenshot](https://user-images.githubusercontent.com/36825711/208232648-ddea349f-d061-4579-a8df-840e09b9e79f.PNG)

**Comment by dr413677671** [comment]
I could repro by manually delete the directory. The subdirectory might not be sucessfully created in webui on your env.
Thanks for report this issue. Could you help confirm:
1. D:\\xxx\\xxxxxxxx\\stable-diffusion-webui\\extensions\\PromptGallery-stable-diffusion-webui\\assets\\preview\\* is not readonly.
2. Is folder "General_ice_high_res" is generated?
3. Could you try remove param xformers and deepdanbooru.

**Comment by Falls-From-Tree** [comment]
Sure,
1. Confirmed it is not readonly
2. it is generated
3. I just removed the other params and tried and still got the error

**Comment by dr413677671** [comment]
Yes. My temp file do not generated with any prompt attachment. Did you tried git pull to upgrade AUTOMATIC1111 webui?
![image](https://user-images.githubusercontent.com/32362729/209125125-9a40c139-6f35-4a95-b272-da121b79fc30.png)

**Comment by dr413677671** [comment]
@Falls-From-Tree I could repro this.
This is a path error from windows. It could not write to a very long path. I added a fix to the filepath. Please update the extension.
