### ISSUE TITLE
Cannot customize avatars and tags

### ISSUE THREAD

**Issue by ghost** [dr413677671/PromptGallery-stable-diffusion-webui#13]
I modified avatars.yaml and tags.yaml but the extension doesn't update after refresh or reboot webui and remain as default template.

![image](https://user-images.githubusercontent.com/116138278/209166003-44bb2207-4ec5-43f7-a96c-954beef4e35d.png)

**Comment by ghost** [comment]
Oh I just tried cleaning cookie and browse history the problem was solved
Not sure if it is actually related or just dumb luck....

**Comment by dr413677671** [comment]
It might be related. But I am not able to repro to find out the root cause. The yaml should be dynamically request.

**Comment by dr413677671** [comment]
Closing. Please let me know it happens again.
