### ISSUE TITLE
script breaks model selector

### ISSUE THREAD

**Issue by muunkky** [dr413677671/PromptGallery-stable-diffusion-webui#14]
So, I'm actually working on a pull request to add support for model ckpt selection in the params (I can see why this was not included). While debugging I found something interesting, using the script actually breaks the model selector. Once you generate images with this script on, the model selector no longer changes the model weights.

Can you see if you can reproduce?

1. open automatic1111
2. open Prompt Gallery script
3. Load avatar and tag yamls with no errors
4. click Generate
5. Images generate with no errors
6. change the model selector at the top of the UI
7. Model changes instantly (no delay)
8. CMD terminal does not do anything
9. Click Generate
10. Images generate with no errors BUT they are generated with the old model

I tried debugging a little but couldn't find anything. Perhaps the p_copy variable is overriding the default settings in the shared StableDiffusionProcessing variable?

**Comment by dr413677671** [comment]
Thanks. Will try to debug this.
At the same time you could WAR by uncomment lines with sd_model in the extension script. Add model hash as a param in the yaml file.

**Comment by dr413677671** [comment]
This will specified the model seleted for each trial.

**Comment by dr413677671** [comment]
This is a framework issue. If you select any of the script and stop at the middle of the generation. This error happens.
If the generation completed. The model selection is ok to work.

**Comment by dr413677671** [comment]
Closed as not a fix for extension.
