### ISSUE TITLE
Google Colab Support

### ISSUE THREAD

**Issue by R-N** [dr413677671/PromptGallery-stable-diffusion-webui#15]
It fails to connect to localhost (of course). I'm using cloudflared tunnel to load sdwebui. I tried tunneling the gallery too (at localhost:5173) to open it separately, but it doesn't work. It seems that it shuts down because it failed to bind.

```
INFO:     Started server process [28361]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 5173, 0, 0): cannot assign requested address
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
```

**Comment by dr413677671** [comment]
I think port 5173 is not opened on colab. Please change port number 5173 to a different number in this [script](https://github.com/dr413677671/PromptGallery-stable-diffusion-webui/blob/main/scripts/prompt_gallery.py).

**Comment by dr413677671** [comment]
Please checkout the Readme where update some instructions on customize ip and port.
