### ISSUE TITLE
[enhancement] add new prompt from ui

### ISSUE THREAD

**Issue by DougStoker** [dr413677671/PromptGallery-stable-diffusion-webui#18]
editing the yaml is more effort than just keeping your prompts in a notes app

**Comment by dr413677671** [comment]
I do not agree. There are tons of tools on the internet to help you edit yaml like Quick YAML Editor.
Notes app is not structral!!!!!

**Comment by DougStoker** [comment]
No, I'm saying it's currently not worth the effort to use this extension at all for storing prompts
