### ISSUE TITLE
Can't see extension in UI

### ISSUE THREAD

**Issue by ClashSAN** [dr413677671/PromptGallery-stable-diffusion-webui#2]
I'm having trouble seeing the extension the webui, perhaps it is an issue with the folder structure?
The script and tab does not show up for me. Im using https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/4b3c5bc24bffdf429c463a465763b3077fe55eb8

**Comment by dr413677671** [comment]
Hi @ClashSAN I run a Virtual Machine windows and do the installation.
It looks fine on my machine. I would suggest you check and make sure:
1.1 <prompt_gallery_directory>/extension/* is paste to /extension/.
1.2 <prompt_gallery_directory>/script/* is paste to /script/.

![image](https://user-images.githubusercontent.com/32362729/205072174-d4729b08-9565-4b84-b284-ca835b5475cd.png)

**Comment by dr413677671** [comment]
Please let me know if it doesn't work.

**Comment by ClashSAN** [comment]
@dr413677671 I'm sorry, I didn't explain the steps to you.

I cloned your repository using the "install from url" section, then I restarted the webui.
Since most Extensions at this point are scripts that work immediately without the user moving folders around, I immediately thought it wasn't working. But if there is a way you know to move the files to their correct points automatically, it would be ideal, as many users will think it is broken :safety_pin:

**Comment by ClashSAN** [comment]
I see there are two scripts needed. I think having an install.py will help, you say you may need to install with `pip install -r requirements.txt` The install.py should install any packages so that the user doesn't have to. You can also run code to move the file from your repository to the Scripts section. Example install.py:

    import launch

    if not launch.is_installed("pyyaml"):
        launch.run_pip("install pyyaml", "requirements for Prompt Gallery")
    
If you want leave moving folders to the user, it's fine. But I think a warning should be given or users will be confused or complain.

**Comment by dr413677671** [comment]
Hey pal,

Thanks for the advice.

Just verified it is ok. Pyyaml should be installed by webui already. requirements.txt is not needed.

I added the setup.py. This should be one-shot install now.

**Comment by ClashSAN** [comment]
It has to be specifically named `install.py` for webui to trigger, If you put your github link in the "install from url", download, and click apply and restart webui, you can test if it's going to work.
I tried renaming setup.py and reloading, but it doesn't move the folders yet.

**Comment by dr413677671** [comment]
Got it clear. I added install.py and changed the readme. It should be working now by webui install.

**Comment by ClashSAN** [comment]
It's showing up now, so we can add it to the index, you did fix it.

**Comment by ClashSAN** [comment]
Let me know if the description needs changing: 

"Build a yaml file filled with prompts of your character, hit generate, and quickly preview them by their word attributes and modifiers."

**Comment by dr413677671** [comment]
That looks great.   (๑•̀ㅂ•́)و✧
