### ISSUE TITLE
BUG: Does not correctly parse sampler index

### ISSUE THREAD

**Issue by chrisesler** [dr413677671/PromptGallery-stable-diffusion-webui#24]
when I enter a sampler in the param, it does not map correctly to sampler index. Always defaults to 1 (1 == Euler)

Looking at code for the parse param there is a elseif check that is incorrect

`elif value == 'Sampler':
            m_sampler_index = map_sampler_to_idx[value]`
            
 You are checking if the value is Sampler, when it should be 'key'
 
 Correction should be:
 
`elif key == 'Sampler':
            m_sampler_index = map_sampler_to_idx[value]`

**Comment by dr413677671** [comment]
Thanks @chrisesler. Fixed.
