### ISSUE TITLE
Use multiple models?

### ISSUE THREAD

**Issue by offroadguy56** [dr413677671/PromptGallery-stable-diffusion-webui#29]
Is it possible to use multiple models when generating the gallery images? At the moment I'd like to put the models I have collected on display and show how they perform based on parameters. 

I've tried slipping this into the tags.yaml but it didn't seem to change the model from what was already selected at the top left of the web ui. At least it didn't throw any errors. 

The Example:
`Anime:`
  `  Fox:`
    `    "AnythingV3":`
      `      value: "masterpiece, best quality, fox, anthro"`
      `      negative: "lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry"`
      `      param: "Model: anythingv3, Steps: 35, Sampler: Euler a, CFG scale: 7, Seed: 1058629707, Size: 512x768, Variation seed: 1692844643, Variation seed strength: 0.27, Seed resize from: 1088x512"`

I have a lot of models I really don't want to generate them one by one and have to shuffle images and add parameters and stuff to the yaml to keep things organized.

**Comment by dr413677671** [comment]
Did you try select the model at the top left of the webui. Added the model in param is not working currently because of working around a bug.

**Comment by dr413677671** [comment]
Close it. Please use the tab
<img width="275" alt="image" src="https://github.com/dr413677671/PromptGallery-stable-diffusion-webui/assets/32362729/6200d4c5-5667-4f2f-98cf-81359c8f23d4">
