### ISSUE TITLE
Feature Request: Option to show selected avatars image on all cards

### ISSUE THREAD

**Issue by WorldEntityGravity** [dr413677671/PromptGallery-stable-diffusion-webui#33]
Hi, first off all, I love the structure this extension provides for keeping track of different styles. However, one thing that I find annoying is having to click through each image of a card to display a specific avatar. The problem then amplifies when you want to compare different prompts with the same (non-default) avatar.

So one solution could be to have a option to switch all images on the cars to a specific avatar, either when clicking on the avatar button or a separate controller (drop-down box or similar) to select which avatar to view.

**Comment by dr413677671** [comment]
Hi @WorldEntityGravity it is a very good idea. I have support this feature in [support toggle avatar](https://github.com/dr413677671/PromptGallery-stable-diffusion-webui/commit/d6dde08581d5bc2773ffb3b98a41ca58155af01c)

Please reinstalled the extension and try click the avatar on the top to toggle avatars in all previews.

**Comment by WorldEntityGravity** [comment]
It works perfectly! Thank you for such quick response 🥇
