### ISSUE TITLE
Size param not working

### ISSUE THREAD

**Issue by IronTulip** [dr413677671/PromptGallery-stable-diffusion-webui#36]
`parse_size` doesn't return anything, which seems to be a bug.

https://github.com/dr413677671/PromptGallery-stable-diffusion-webui/blob/148c188fc2459de47646159f5bcaeda036b68cf6/paste_this_to_webui_scripts_folder/prompt_gallery.py#L272-L274
```python            
def parse_size(str_size):
    i_width, i_height = str_size.split('x')
    return i_width, i_height
```
https://github.com/dr413677671/PromptGallery-stable-diffusion-webui/blob/148c188fc2459de47646159f5bcaeda036b68cf6/paste_this_to_webui_scripts_folder/prompt_gallery.py#L308-L309
```python
        elif key == 'Size':
            m_width, m_height = parse_size(value)
```

**Comment by dr413677671** [comment]
Added fix [fix param](https://github.com/dr413677671/PromptGallery-stable-diffusion-webui/commit/5e28ec34dabc625b38e7a967471f9d4dbda133ec). Could you have a look is this resolved？
