### ISSUE TITLE
not working with black mode

### ISSUE THREAD

**Issue by IkariDevGIT** [dr413677671/PromptGallery-stable-diffusion-webui#4]
![grafik](https://user-images.githubusercontent.com/90197782/205448504-bc0d58e1-ef06-435e-a4d8-07dc4c216dce.png)

**Comment by dr413677671** [comment]
Hi Ikari,

Thanks for the issue.

Added a fix today. It it adapted to dark theme automatically. :wink:

![image](https://user-images.githubusercontent.com/32362729/205481868-05e188ef-cf90-472b-a19d-710a1af7e7bb.png)

**Comment by dr413677671** [comment]
Please feel free to reinstalled it and have a try.

**Comment by dr413677671** [comment]
@IkariDevGIT Could this close?
