### ISSUE TITLE
Could not get it to work, not showing generated images after "select".

### ISSUE THREAD

**Issue by RafaRed** [dr413677671/PromptGallery-stable-diffusion-webui#6]
It looks very interesting to me, but unfortunately I couldn't get it to work, even trying for hours and even looking at the code.

I'm sending a video showing the structure of the folders it generated (installing manually and following the installation guide step by step), I've already tried automatic installation through the "Available" tab, and I wasn't successful either.

Apparently when I'm pressing select, the files disappear from the preview folder and don't go anywhere, I imagine they should go to some folder right?

Video: 
https://youtu.be/OQYz4d5cyKk

**Comment by dr413677671** [comment]
Hi RafaRed

My bad. I think following the readme it will install two prompt galleries.

I had fixed the readme. Please try delete the "Prompt Gallery" and "prompt-gallery" in the extension folder. Then follow [readme](https://github.com/dr413677671/PromptGallery-stable-diffusion-webui). Only use the webui install function.

**Comment by dr413677671** [comment]
Please also delete the prompt_gallery_name.json

**Comment by RafaRed** [comment]
@dr413677671 actually, it created the file pormpt-gallery when start to run the script.

lines 41 and 42

OUTPATH_SAMPLES = './extensions/prompt-gallery/assets/preview/'
OUTPATH_GRIDS = './extensions/prompt-gallery/assets/grid/'

this should be "Prompt Gallery", right?

**Comment by RafaRed** [comment]
When I start to run the script it downloads the files "whiteHair_0" and whiteHair_1" and ask me to save it, but i dont know where to save this files and give me an error probablly in lines 41 and 42 of the script.



![error](https://user-images.githubusercontent.com/28813496/205631272-f04635d8-12bc-4a8a-8582-64bd67f67a93.jpg)

**Comment by RafaRed** [comment]
@dr413677671 I see that you did some changes on the script to fix that, thanks.
now its not creating 2 folders, but still not working when I use the "select" button, just delete the files inside the preview folder and the "404 image" on the Prompt Gallery still there, did not override for the selected one.

**Comment by dr413677671** [comment]
Hi mate,

My silly mistake indeed.🤣

Thanks for helping stablelzing it. 

I run a test E2E. Should be good now.

**Comment by dr413677671** [comment]
Still Bug, debugging

**Comment by RafaRed** [comment]
@dr413677671 Yeah, 

1. When I selected the PinkGirl asked me to download 2 files pinkGirl_0 and pinkGirl_1, i dont know where to save then.
2. When I click "select" still delete the preview images, but do not add then to my "Prompt Gallery", they should move to another folder when I click "select"? I need to use the "auto rename"?

**Comment by dr413677671** [comment]
Yes, should be working now
1. It will download to your default download path. If you are using chrome. In configuration you need to select "ask me everytime when download..." then path selection pop up.
2. This time it fixed. WebUI seems to added a comma filter in filename blob. Fixed that in extension.

**Comment by dr413677671** [comment]
The filepath error are killers.

**Comment by RafaRed** [comment]
@dr413677671 Nice! Now its working. Thank you for fixing & for the extention.

obs: I don't know if were indented or your just forgot to remove the "print's" for the renames etc.

**Comment by dr413677671** [comment]
Removed 😋
